apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-nginx
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/apps/demo-nginx
  prune: true
  dependsOn:
    - name: infrastructure
    - name: sources
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
