apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "6.4.22"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    installCRDs: true
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.26.225-192.168.26.235